export const errors = {
    en: {
       
        "accountAlreadyExist": "Account with given Phone number and Role already exist.",
        "noSuchAccountExist": "No such account exist.",
        "invalidMongoId": "{{key}} must be a valid mongo ID",
        "noDatafound": "No Record Found",
        "alreadyExist": "An account with given phoneNumber or email already exists",
        "Exists": "Already Exists! Please try again",
        "userExist": "User already Exist",
       
    }
}

export const success = {
    en: {
        "signupSuccessful": "Signup sucessfully",
        "loginSuccessful": "Login sucessfully",
        "accountExists": "Account already exist",
        "noSuchAccountExist": "No such account exist",
        "respondSuccess": "You have responded successfully",
        "RecordFound": "Record found",
        "issueReported": "issue Reported Successfully",
        "logOutSuccessful": "User logOut successfully",
        "userComment": "User Comments successfully",
        "accountCheckSuccessful": "Account Checked Successfully",
        "otpSendSuccessful": "Otp Send Successfully",
        "otpverifysuccessful": "Otp Verified Successfully",
        "succssDefault": "Success",
        "recordFetched": "Record fetched sucessfully",
        "reviewUpdate": "Review has been updated successfully",
        "reviewSubmit": "Review has been submitted successfully"
    }
}

